from typing import Protocol


class GameRepository(Protocol):
    def create(self, document: dict) -> None: ...
    def get(self, game_id: str) -> dict | None: ...
    def update_state(self, game_id: str, expected_version: int, document: dict) -> bool: ...
    def finish(
        self, game_id: str, expected_version: int, document: dict, status: str, winner: str | None
    ) -> bool: ...
    def assign_black_player(self, game_id: str, player: dict) -> bool: ...
    def start_clock(self, game_id: str, timestamp) -> bool: ...
    def list_active(self, limit: int = 200) -> list[dict]: ...
