from typing import Protocol


class RoomRepository(Protocol):
    def create(self, document: dict) -> None: ...
    def get(self, room_code: str) -> dict | None: ...
    def list_public(self, limit: int, skip: int, mode: str | None = None) -> list[dict]: ...
    def assign_black_player(self, room_code: str, player: dict) -> bool: ...
    def add_spectator(self, room_code: str, spectator: dict, limit: int) -> bool: ...
    def remove_spectator(self, room_code: str, token_hash: str) -> bool: ...
    def update_metadata(self, room_code: str, metadata: dict) -> bool: ...
    def find_by_game(self, game_id: str) -> dict | None: ...
    def touch(self, room_code: str, timestamp, status: str | None = None) -> bool: ...
    def mark_finished(self, room_code: str, expires_at) -> bool: ...
