from typing import Protocol


class UserRepository(Protocol):
    def create_user(self, document: dict) -> None: ...
    def get_user(self, user_id: str) -> dict | None: ...
    def get_by_username_key(self, username_key: str) -> dict | None: ...
    def update_user(self, user_id: str, update: dict) -> bool: ...
    def create_session(self, document: dict) -> None: ...
    def get_session(self, session_hash: str) -> dict | None: ...
    def touch_session(self, session_hash: str, last_used_at) -> bool: ...
    def revoke_session(self, session_hash: str, revoked_at) -> bool: ...
    def revoke_all_sessions(self, user_id: str, revoked_at) -> int: ...
    def replace_recovery_codes(self, user_id: str, documents: list[dict]) -> None: ...
    def get_recovery_codes(self, user_id: str) -> list[dict]: ...
    def mark_recovery_used(self, user_id: str, code_id: str, used_at) -> bool: ...
    def record_result(self, document: dict) -> bool: ...
    def list_results(self, user_id: str) -> list[dict]: ...
